name: crowdin_sdk
description: A new Flutter package project.
version: 0.1.0
repository: https://github.com/crowdin/flutter-sdk
homepage:

environment:
  sdk: '>=2.12.0 <3.14.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  intl: ^0.17.0
  shared_preferences: ^2.0.4
  connectivity_plus: ^2.1.0
  yaml: ^3.1.1
  meta: ^1.7.0
  path: ^1.8.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.3.2
  build_runner: 2.3.3
  flutter_lints: 1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
#flutter:
#  generate: true

